### ISSUE TITLE
mac?

### ISSUE THREAD

**Issue by alexshepard** [icanzilb/MTLog#1]
any reason the MTLog pod is iOS only?

```
[!] The platform of the target `Pods` (OS X 10.7) is not compatible with `MTLog (0.6.1)` which has a minimum requirement of iOS 6.0.
```

**Comment by icanzilb** [comment]
Hi alex, there's no reason ... it's just the very fist version of this lib, and things are still being polished ...
Did you test it on OSX?

**Comment by alexshepard** [comment]
I suppose I should have tried it first :)

 -firstObject on NSArray is an iOS only thing. Mac has -lastObject and of course -objectAtIndex:

http://troybrant.net/blog/2010/02/adding-firstobject-to-nsarray/

I guess if you wanted to support Mac, you could switch to -objectAtIndex:, or add a category to NSArray that's only imported on Mac. Or I could give you a pull request if you'd like.

**Comment by icanzilb** [comment]
oh well, firstObject is used on only 1 place, and it should be pretty safe to use just [0] there. I'd say - send me a pull

**Comment by alexshepard** [comment]
it looks to me like it's in five files in plugins/:

→ git diff --stat
 MTLog/plugins/MTLogPluginPrefix.m   | 4 ++--
 MTLog/plugins/MTLogPluginRegister.m | 4 ++--
 MTLog/plugins/MTLogPluginRemove.m   | 2 +-
 MTLog/plugins/MTLogPluginRoute.m    | 4 ++--
 MTLog/plugins/MTLogPluginSearch.m   | 4 ++--
 5 files changed, 9 insertions(+), 9 deletions(-)

→ grep -lr firstObject .
./MTLog/plugins/MTLogPluginPrefix.m
./MTLog/plugins/MTLogPluginRegister.m
./MTLog/plugins/MTLogPluginRemove.m
./MTLog/plugins/MTLogPluginRoute.m
./MTLog/plugins/MTLogPluginSearch.m
./MTLogDemo/ViewController.m
./MTLogDemoTests/tests/MTLogRouteTests.m
./README.md

**Comment by icanzilb** [comment]
merged, I'll test it myself as well later on.
I wonder why it's firstObject not on the osx though?
