### ISSUE TITLE
iOS5 Support

### ISSUE THREAD

**Issue by inamiy** [icanzilb/MTLog#5]
Current podspec only supports iOS6 or higher,
but it will be glad if you can also support iOS5 for legacy apps :)

**Comment by icanzilb** [comment]
yup, fair enough - I think it should work on iOS5 out of the box anyway, I'll look into testing this

**Comment by icanzilb** [comment]
actually I've no idea even how to test for this...

**Comment by icanzilb** [comment]
it seems to compile for iOS5, but can't test since there's no more iOS5 simulators integrated in xcode ... will just change the cocoapod spec I guess

**Comment by inamiy** [comment]
Yes, I also guess just changing to `s.ios.deployment_target = '5.0'` will be all fine.
If you need a test, you can still grab old Xcode 4.6.3 from developer center.
