### ISSUE TITLE
Remove date and application name from output

### ISSUE THREAD

**Issue by qizh** [icanzilb/MTLog#6]
Is there an option to do that?

**Comment by icanzilb** [comment]
are you asking how to remove the prefix and have only the string you pass to NSLogin the output?

**Comment by icanzilb** [comment]
Is it this you're looking for? https://github.com/icanzilb/MTLog#_prefixset-1

**Comment by qizh** [comment]
No. I'm having log like this:

```
2013-10-07 10:16:18.623 appname[4686:a0b] myMethod 20 > My log message!
```

But I wish to have log like this:

```
myMethod 20 > My log message!
```

**Comment by icanzilb** [comment]
oh no, that first part is added by the OS as far as I know. because you know - on the actual device all these log messages get together in the log so that's why there's also the app name and the time.

but I agree with you - when you debug in xcode is really annoying that the half width of the output console is taken by this ...

**Comment by qizh** [comment]
This info is added by original NSLog function. You can disable that by doing something like

```
#define NSLog(STRING, ...) printf("%s\n", [[NSString stringWithFormat:STRING, ##__VA_ARGS__] UTF8String]);
```

But I was wondering whether there is an option in this code to perform that.

**Comment by icanzilb** [comment]
well I overwrite the original NSLog, so it must be coming from somewhere else ...

**Comment by qizh** [comment]
You are using `NSLogv` to make final output to console but you should use `printf` to avoid that date logging stuff. Or at least you should make it an option.

**Comment by icanzilb** [comment]
hmmm ... that sounds interesting, I'll look into that, that's an awesome idea

**Comment by icanzilb** [comment]
sorry it took me so long to get around this, so busy these days :[
